os: osx
language: node_js
node_js:
  - node
  - lts/*
before_install: export PATH="$PATH:$(yarn global bin)"
install: yarn
before_script: yarn global add electron-builder
script: true
after_script: yarn dist
deploy:
  provider: releases
  api_key: $GH_TOKEN
  file:
  skip_cleanup: true
  on:
    tags: true
    node: lts/*
